// Talking Hearts — 200 original date-night questions.
// Grouped by theme; the app shuffles them all together.

const cat = (category, items) => items.map((q) => ({ q, category }))

export const DECK = [
  ...cat('Icebreakers', [
    'What was the first thing you noticed about me?',
    'If we had a theme song, what would it be?',
    'What three words would you use to describe us?',
    'What is your favourite thing we do together on a lazy day?',
    'What did you think of me when we first met — honestly?',
    'What is a small thing I do that always makes you smile?',
    'If our relationship were a movie genre, what would it be?',
    'What is your idea of a perfect evening together?',
    'What nickname would you give us as a couple?',
    'What is a song that reminds you of me?',
    'What is your favourite photo of us, and why?',
    'If we opened a business together, what would it be?',
    'What is a tiny ritual we have that you love?',
    'What smell or taste reminds you of us?',
    'What would you title the current chapter of our life?',
    'What is the most "us" thing we have ever done?',
    'If our week had a highlight reel, what would be on it?',
    'What is a place that feels like "ours"?',
    'What is something you would love us to be known for?',
    'What is your favourite way I say your name?',
  ]),

  ...cat('Early Days', [
    'What do you remember most about the day we met?',
    'When did you first realise you had feelings for me?',
    'What was going through your head on our first date?',
    'What almost stopped us from getting together?',
    'What is a moment early on that you keep coming back to?',
    'What did you tell your friends about me at the start?',
    'What first attracted you to me, beyond looks?',
    'Was there a moment you knew this was different?',
    'What is something you were nervous about early on?',
    'What is a "first" we shared that you will never forget?',
    'If you could relive one early memory of us, which would it be?',
    'What surprised you most about me once we got closer?',
    'What did the early version of me get right?',
    'What is a message or call from back then you wish you had saved?',
    'When did you first say "I love you" in your head, before out loud?',
    'What did falling for me feel like?',
    'What is a risk you took to be with me?',
    'What did you hope for us in the very beginning?',
    'What has changed most about us since day one?',
    'What has stayed exactly the same since the start?',
  ]),

  ...cat('Our Memories', [
    'What is the hardest we have ever laughed together?',
    'What trip or outing do you wish we could redo?',
    'What is a small moment that meant more than a big one?',
    'What is a memory of us that still makes you emotional?',
    'What is the best meal we have ever shared?',
    'What adventure do we need to go on again?',
    'What is a mistake we made that we can laugh about now?',
    'What is a time I made you feel really cared for?',
    'What ordinary day with me would you relive?',
    'What is the proudest moment we have shared?',
    'What challenge did we get through together that you are glad we did?',
    'What is a photo we never took that you wish we had?',
    'What is a tradition we have built that you treasure?',
    'What is the most spontaneous thing we have done?',
    'What is a moment you felt truly a team with me?',
    'What song will always take you back to a moment with us?',
    'What gift between us has meant the most?',
    'What is the coziest night we have spent together?',
    'What is a place we have been that you would return to tomorrow?',
    'What is a memory you hope we never forget?',
  ]),

  ...cat('Everyday Us', [
    'What is your love language, and do you think I speak it well?',
    'How do you most like to be comforted after a bad day?',
    'What is a small gesture that makes you feel loved?',
    'What does a perfect Sunday look like for you?',
    'How do you recharge when you are drained?',
    'What is something you wish I asked you about more?',
    'What makes you feel most appreciated?',
    'What is your favourite way to spend time with me?',
    'What is a food you could never give up?',
    'How do you like to celebrate wins?',
    'What helps you feel safe with someone?',
    'What is a habit of mine you secretly like?',
    'What is your idea of a treat?',
    'What kind of touch feels most reassuring to you?',
    'What is something small I could do this week to make you happy?',
    'How do you prefer to resolve a disagreement?',
    'What is your favourite part of our daily routine?',
    'What makes you feel truly listened to?',
    'What is a comfort you never want to compromise on?',
    'What is something you would love more of in our everyday life?',
  ]),

  ...cat('Heart to Heart', [
    'When do you feel closest to me?',
    'What is something you find hard to say out loud?',
    'What is a fear about us that we could talk through together?',
    'When have you felt most supported by me?',
    'What do you need from me when you are struggling?',
    'What is something you are proud of that you do not say enough?',
    'What makes you feel emotionally safe with me?',
    'What is a part of your past that still shapes you?',
    'When do you feel most understood?',
    'What is a compliment you wish you heard more?',
    'What is something you are working through right now?',
    'What does trust look like to you?',
    'When have you felt most vulnerable with me, in a good way?',
    'What is a way I could show up better for you?',
    'What do you worry about when it comes to love?',
    'What is a truth about yourself you are still learning to accept?',
    'When do you feel most like yourself around me?',
    'What is something you have forgiven that was hard to?',
    'What helps you open up?',
    'What is a feeling you have had lately that you have not shared?',
  ]),

  ...cat('Romance', [
    'What makes you feel most desired?',
    'What is your favourite way to be kissed?',
    'What is a romantic gesture you secretly wish for?',
    'When do you find me most attractive?',
    'What always puts you in a loving mood?',
    'What is a memory of us that still gives you butterflies?',
    'What is your idea of the perfect slow dance?',
    'What do you love about the way we are close?',
    'What is a dream date you have never told me about?',
    'What makes a moment feel intimate to you?',
    'What is your favourite thing to whisper, or to hear whispered?',
    'When do you feel most connected to me?',
    'What is a little flirtation you love?',
    'What is the most romantic place you would love to go with me?',
    'What is something of mine you love seeing me in?',
    'What is a way we could add more spark to our week?',
    'What is your favourite kind of affection?',
    'When do you feel most cherished?',
    'What is something tender you would like more of?',
    'What is a moment you would love to recreate, just us?',
  ]),

  ...cat('Dreams & Future', [
    'Where do you see us in five years?',
    'What is a dream you want us to chase together?',
    'What does "home" look like to you with me?',
    'What adventure is still on your list for us?',
    'What kind of older couple do you hope we become?',
    'What tradition do you want us to start?',
    'What is something you want us to learn together?',
    'What would a perfect ordinary day in our future look like?',
    'What is a goal of mine you would love to help me reach?',
    'What place do we absolutely have to visit one day?',
    'What do you hope never changes about us?',
    'What do you want our home to always feel like?',
    'What is a promise you would like us to make?',
    'What does growing together mean to you?',
    'What is a milestone you are excited for?',
    'What is a dream you set aside that I could help you revive?',
    'What kind of memories do you want us making next year?',
    'What is something brave you would like us to do together?',
    'If we designed our ideal life, what would be non-negotiable?',
    'What legacy do you want us to build?',
  ]),

  ...cat('Just for Fun', [
    'If we could teleport anywhere right now, where would we go?',
    'What would our reality TV show be called?',
    'If you planned a surprise for me, what would it be?',
    'What superpower would you want us to have as a couple?',
    'If we swapped lives for a day, what would you do?',
    'What is the most ridiculous thing you would do to make me laugh?',
    'If we won the lottery tonight, what is the first thing we do?',
    'What would be on our dream road-trip playlist?',
    'If we had a mascot animal, what would it be?',
    'What is a silly bet we should make right now?',
    'If we opened a food truck, what would we sell?',
    'What is the weirdest talent you wish we shared?',
    'If our love were a flavour of ice cream, what would it be?',
    'What is a dare you would give me right now?',
    'If we could master any skill instantly, what would we pick?',
    'What would your "best partner" acceptance speech say about me?',
    'If we had a secret handshake, what would be in it?',
    'What themed party should we throw together?',
    'If we were characters in a story, who would we be?',
    'What is the most fun rule we should add to date night?',
  ]),

  ...cat('What We Value', [
    'What does a strong relationship mean to you?',
    'What value do you never want us to lose?',
    'How do you want us to handle hard times?',
    'What have you learned about love from us?',
    'What is a way you have grown since we have been together?',
    'What does respect look like day to day for you?',
    'How do you want us to support each other’s dreams?',
    'What is a boundary that matters to you?',
    'What does forgiveness mean in a relationship?',
    'How do you want us to keep growing closer?',
    'What is a lesson from your family you want to keep, or leave behind?',
    'What does loyalty mean to you?',
    'How do you define a good partner?',
    'What is something you want us to always make time for?',
    'What role should honesty play, even when it is hard?',
    'What do you want us to teach others by example?',
    'How do you want to handle dreams and plans together?',
    'What is a way we can be a better team?',
    'What does commitment feel like to you?',
    'What is one thing you want us to promise to protect?',
  ]),

  ...cat('Gratitude', [
    'What is something about me you are grateful for today?',
    'When did I last make your day better without knowing it?',
    'What is a strength of mine you admire?',
    'What is something I do that you never want me to stop?',
    'How have I helped you become a better version of you?',
    'What is a sacrifice I made that you noticed?',
    'What do you appreciate about how we handle conflict?',
    'What is a quality in me you are thankful for?',
    'When have you felt most proud to be with me?',
    'What is something small I did recently that meant a lot?',
    'What do you love about our life together right now?',
    'What is a way I show up that you can count on?',
    'What part of me are you glad you get to see that others do not?',
    'What is a moment you felt lucky to have me?',
    'What would you thank me for if you thought of it more often?',
    'What do you value most about our friendship?',
    'What is a way I have surprised you for the better?',
    'What is a comfort I bring to your life?',
    'What is something about us you would never trade?',
    'What are you most grateful for about us this year?',
  ]),

  ...cat('Would You Rather', [
    'Would you rather have a lazy pyjama day or a spontaneous adventure?',
    'Would you rather always be 10 minutes early or 10 minutes late?',
    'Would you rather give up coffee or dessert forever?',
    'Would you rather visit the past or the future for a day?',
    'Would you rather win a dance-off or a karaoke battle?',
    'Would you rather have a personal chef or a personal masseuse?',
    'Would you rather explore space or the deep sea together?',
    'Would you rather be able to teleport or read minds?',
    'Would you rather host the party or be a guest at it?',
    'Would you rather have a pause button or a rewind button for life?',
    'Would you rather live by the beach or in the mountains?',
    'Would you rather be famous or secretly filthy rich?',
    'Would you rather sing everything you say or dance everywhere you go?',
    'Would you rather have unlimited flights or unlimited hotel stays?',
    'Would you rather eat only sweet or only savoury for a year?',
    'Would you rather relive our first date or jump to a dream one?',
    'Would you rather have a pet dragon or a pet unicorn?',
    'Would you rather be the funniest or the smartest person in the room?',
    'Would you rather always know the truth or always be pleasantly surprised?',
    'Would you rather have a cosy night in or a big night out?',
  ]),

  ...cat('Silly & Random', [
    'If you were a kitchen appliance, which one would you be?',
    'What totally useless talent are you weirdly proud of?',
    'What is the strangest thing you find attractive?',
    'If our pet could talk, what would it say about us?',
    'What is your most irrational fear?',
    'What emoji describes your mood right now?',
    'If you had to eat one meal for the rest of your life, what is it?',
    'What is the silliest argument we have ever had?',
    'What is a conspiracy theory you low-key believe?',
    'If aliens landed, what is the first thing you would show them?',
    'What is your go-to karaoke song?',
    'What would your superhero name and power be?',
    'What is the weirdest thing you have eaten and actually liked?',
    'If you were a cocktail, what would be in you?',
    'What is the most embarrassing song on your playlist?',
    'What childhood cartoon would you still happily watch today?',
    'What is a food combination you love that others find gross?',
    'What is the last thing that made you laugh out loud?',
    'If we started a band tonight, what would we be called?',
    'What is the most ridiculous thing you have googled?',
  ]),

  ...cat('Flirty & Fun', [
    'What is the cheesiest pick-up line you would actually fall for?',
    'What is something I do that is unfairly cute?',
    'Describe me in one flirty word.',
    'What is your favourite way to be teased?',
    'What outfit makes you feel unstoppable?',
    'What compliment would make you blush right now?',
    'What is the most charming thing I have ever done?',
    'What is a little crush-feeling you still get about me?',
    'What emoji would you text me right now?',
    'What is the flirtiest text you have ever sent?',
    'What is your idea of playful trouble on a date night?',
    'What is something you would dare me to do right now?',
    'What is a look I give that you love?',
    'What is the best kind of surprise kiss?',
    'If tonight were a date, how would you want it to end?',
  ]),
]
